development:
    adapter: postgresql
    encoding: unicode
    database: BookShop
    pool: 2
    username: dvec95
    password: your_password

production:
    adapter: postgresql
    encoding: unicode
    pool: 5
    host: <%= ENV['DATABASE_HOST'] %>
    database: <%= ENV['DATABASE_NAME'] %>
    username: <%= ENV['DATABASE_USER'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>